name: Run tests

on:
  pull_request:
    branches: [ 'main' ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run Gradle Tests
        run: ./gradlew test